# Generated by Django 2.2.5 on 2019-09-20 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
                ('descricao', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('data_nacimento', models.DateField(verbose_name='Data de Nascimento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_biblioteca.Pessoa')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matricula')),
            ],
            bases=('app_biblioteca.pessoa',),
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Título')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
                ('isbn', models.CharField(max_length=20, verbose_name='isnb')),
                ('ano_public', models.IntegerField()),
                ('edicao', models.CharField(max_length=15, verbose_name='Edição')),
                ('editora', models.CharField(max_length=20, verbose_name='Editora')),
                ('tipo', models.BooleanField(default=False, verbose_name='É digital?')),
                ('categoria_livro', models.ManyToManyField(to='app_biblioteca.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pegar', models.DateTimeField(auto_now_add=True)),
                ('data_lim_devo', models.DateField(blank=True, null=True, verbose_name='Data limite para devolver')),
                ('data_efetiva_devolucao', models.DateTimeField()),
                ('livro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_biblioteca.Livro')),
                ('pessoaPegar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pessoas', to='app_biblioteca.Pessoa')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_biblioteca.Funcionario')),
            ],
        ),
    ]
